### ISSUE TITLE
I don't understand about this。

### ISSUE THREAD

**Issue by JesseLiang2020** [profnote/AlgoTrading-PriceImpactOrderFlow#1]
# predicted change in midprice
 dP = impact * b * K / 10 + impact * Fm * ((1-rho)**(K / 10) - 1) - impact * sigma
could you tell me ， Why？

**Comment by profnote** [comment]
The change in the price can be estimated by:
dP = (impact of orderflow on price) * (change in orderflow)

The formula for orderflow is:
![image](https://user-images.githubusercontent.com/44751676/93821124-c22ceb00-fc23-11ea-8ffa-5a1e8eb7345d.png)

And so the change in orderflow can be calculated by:
![image](https://user-images.githubusercontent.com/44751676/93821198-dbce3280-fc23-11ea-9303-aff30e92b2f9.png)

**Comment by JesseLiang2020** [comment]
Thank you for your prompt reply. But I still could not find sigma at the last term of the formula(second formula).Could you give me the link about formula or provide me the Related reference documents.

**Comment by profnote** [comment]
The document is one of my professor's original lecture notes, it cannot be accessed by outsiders so I think I'm not allowed to share.
I think my implementation of the formula might be wrong. We may not need the (impact * sigma) term.
